Algoritmo "1"

Var
     n1: vetor [0..2] de inteiro
     n2: vetor [0..2] de inteiro
     contador,soma: inteiro


Inicio
       para contador de 0 ate 2 faca
       escreval("Digite um número: ")
       leia(n1[contador])
       fimpara
       
       para contador de 0 ate 2 faca
       n2[contador] <- n1[contador]
       fimpara

       
       para contador de 0 ate 2 faca
       escreval("1° - ",n1[contador]," 2° - ",n2[contador])
       fimpara
       
       


Fimalgoritmo