Algoritmo "Covid-19"

Var
    p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15: caracter
    c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13,c14,c15: inteiro
    m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,m11,m12,m13,m14,m15: inteiro
    media,mediana: real

Inicio
       escreval("-------------------------------------------------------------------")
       escreval("Casos e Mortes por Covid-19 ao redor do globo: Países mais afetados")
       escreval("-------------------------------------------------------------------")


       escreval("1° país:")
       leia(p1)
       escreval("Casos do 1° país:")
       leia(c1)
       escreval("Mortes do 1° país:")
       leia(m1)
       
       escreval("2° país:")
       leia(p2)
       escreval("Casos do 2° país:")
       leia(c2)
       escreval("Mortes do 2° país:")
       leia(m2)
       
       escreval("3° país:")
       leia(p3)
       escreval("Casos do 3° país:")
       leia(c3)
       escreval("Mortes do 3° país:")
       leia(m3)
       
       escreval("4° país:")
       leia(p4)
       escreval("Casos do 4° país:")
       leia(c4)
       escreval("Mortes do 4° país:")
       leia(m4)
       
       escreval("5° país:")
       leia(p5)
       escreval("Casos do 5° país:")
       leia(c5)
       escreval("Mortes do 5° país:")
       leia(m5)
       
       escreval("6° país:")
       leia(p6)
       escreval("Casos do 6° país:")
       leia(c6)
       escreval("Mortes do 6° país:")
       leia(m6)
       
       escreval("°7 país:")
       leia(p7)
       escreval("Casos do 7° país:")
       leia(c7)
       escreval("Mortes do 7° país:")
       leia(m7)
       
       escreval("8° país:")
       leia(p8)
       escreval("Casos do 8° país:")
       leia(c8)
       escreval("Mortes do 8° país:")
       leia(m8)
       
       escreval("9° país:")
       leia(p9)
       escreval("Casos do 9° país:")
       leia(c9)
       escreval("Mortes do 9° país:")
       leia(m9)
       
       escreval("10° país:")
       leia(p10)
       escreval("Casos do 10° país:")
       leia(c10)
       escreval("Mortes do 10° país:")
       leia(m10)
       
       escreval("11° país:")
       leia(p11)
       escreval("Casos do 11° país:")
       leia(c11)
       escreval("Mortes do 11° país:")
       leia(m11)
       
       escreval("12° país:")
       leia(p12)
       escreval("Casos do 12° país:")
       leia(c12)
       escreval("Mortes do 12° país:")
       leia(m12)
       
       escreval("13° país:")
       leia(p13)
       escreval("Casos do 13° país:")
       leia(c13)
       escreval("Mortes do 13° país:")
       leia(m13)
       
       escreval("14° país:")
       leia(p14)
       escreval("Casos do 14° país:")
       leia(c14)
       escreval("Mortes do 14° país:")
       leia(m14)
       
       escreval("15° país:")
       leia(p15)
       escreval("Casos do 15° país:")
       leia(c15)
       escreval("Mortes do 15° país:")
       leia(m15)
       
       
       escreval(p1," casos: ",c1," mortes: ",m1)
       escreval(p2," casos: ",c2," mortes: ",m2)
       escreval(p3," casos: ",c3," mortes: ",m3)
       escreval(p4," casos: ",c4," mortes: ",m4)
       escreval(p5," casos: ",c5," mortes: ",m5)
       escreval(p6," casos: ",c6," mortes: ",m6)
       escreval(p7," casos: ",c7," mortes: ",m7)
       escreval(p8," casos: ",c8," mortes: ",m8)
       escreval(p9," casos: ",c9," mortes: ",m9)
       escreval(p10," casos: ",c10," mortes: ",m10)
       escreval(p11," casos: ",c11," mortes: ",m11)
       escreval(p12," casos: ",c12," mortes: ",m12)
       escreval(p13," casos: ",c13," mortes: ",m13)
       escreval(p14," casos: ",c14," mortes: ",m14)
       escreval(p15," casos: ",c15," mortes: ",m15)
       
       media <- ((c1+c2+c3+c4+c5+c6+c7+c8+c9+c10+c11+c12+c13+c14+c15)/15)
       mediana <- ((c7+c8)/2)
       
       escreval("A média de casos é: ",media)
       escreval("A mediana de casos é: ",mediana)
       


Fimalgoritmo