Algoritmo "maior e menor"

Var
   n1,n2: inteiro
   
   


Inicio
       escreval("Digite o primeiro número: ")
       leia(n1)
       escreval("Digite o segundo número: ")
       leia(n2)
       
       se n1>n2 entao
       escreval("O primeiro número é maior que o segundo")
       fimse
       
       se n2>n1 entao
       escreval("O segundo número é maior que o primeiro")
       fimse


Fimalgoritmo