Algoritmo "media"

Var

    media, n1, n2, n3, n4: real

Inicio
      escreval("Digite a primeira nota do aluno")
      leia(n1)
      escreval("Dogite a segunda nota do aluno")
      leia(n2)
      escreval("Digite a terceira nota do aluno")
      leia(n3)
      escreval("Digite a quarta nota do aluno")
      leia(n4)
      
      
      media <- ((n1+n2+n3+n4)/4)
      escreval


               

      

Fimalgoritmo