Algoritmo "trocar variável"

Var
    x,y, aux: inteiro

Inicio
       x <- 15
       y <- 12
       
       escreval("Valor de x antes antes da troca: ", x)
       escreval("Valor de y antes antes da troca: ", y)
       
       //troca de valores
       aux <- x
       x <- y
       y <- aux
       
       escreval("Valor de x depois antes da troca: ", x)
       escreval("Valor de x depois antes da troca: ", y)


Fimalgoritmo